---
- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: 1
  register: apt_cache
- name: dist upgrade
  apt:
    upgrade: dist
  when: apt_cache.changed
- name: reboot
  shell: reboot
  when: apt_cache.changed
- name: wait
  local_action:
    module: wait_for
      host: {{ inventory_hostname }}
      port: 22
      delay: 1
      timeout: 300
  when: apt_cache.changed